#: import get_color_from_hex kivy.utils.get_color_from_hex


WindowManager:
    StartPage:
    TeamPage:
    ResultsPage:
    PostStatsPage:
    InfoPage:
    SettingsPage:
    EditPage:

<MD3Card>:
    style: "elevated"
    elevation: 6
    
<StartPage>:
    name: "start"
    MDLabel:
        text: "D1 Hoops"
        font_size: 60
        color: app.theme_cls.primary_dark
        bold: True
        italic: True
        outline_color: app.theme_cls.primary_light
        outline_width: 3
        halign: "center"

    MDLabel:
        text: "alpha 0.1.0"
        pos_hint: {"center_x": 1.06, "center_y": 0.43}

    MDIconButton:
        icon: "information-outline"
        icon_size: "50sp"
        icon_color: app.theme_cls.primary_color
        on_release:
            app.root.current = "info"
            root.manager.transition.direction = "up"

    MDRaisedButton:
        text: "New Game"
        pos_hint: {"center_x": 0.5, "center_y": 0.18}
        on_release:
            app.root.current = "team"
            root.manager.transition.direction = "left"
            app.update(root.user,root.ai)
    MDRaisedButton:
        text: "Load Game"
        pos_hint: {"center_x": 0.5, "center_y": 0.1}


################################################################################################
################################################################################################


<TeamPage>:
    name: "team"
    md_bg_color: 0,0,0,.78
    GridLayout:
        cols: 1
        size_hint: 1,1
        spacing: "10dp"
        padding: "8dp"
        
        MDLabel:
            text: "Edit Hilltoppers\' Roster"
            color: 1,1,1,1
            #bold: True
            font_size: 22
            pos_hint: {"x":.02, "y":.8}
            height: "75dp"

        MD3Card:
            pos_hint: {"center_x":.5, "top":.8}
            size_hint: 1, None
            height: "250dp"
            spacing: 5
            padding: 10
            md_bg_color: .35,.35,.35,1
            radius: 10
            orientation: "vertical"
            Label:
                size_hint: .5,None
                height: "20dp"
                text: "Starters"
                font_size: 12
                color: .8,.8,.8,1
                pos_hint: {"center_x": .5, "y":0}
            GridLayout:
                cols: 2
                
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: app.name1
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDLabel:
                    size_hint: .15,None
                    height: "15dp"
                    text: "PG"
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint:{"right":1, "y": 0}
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "off: " + str(app.off1) + " | def: " + str(app.deff1) + " | reb: " + str(app.reb1) + " | 3pt: " + str(app.att_three1)
                    font_size: 12
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDTextButton:
                    size_hint: .15,None
                    height:"15dp"
                    font_size: "13sp"
                    on_release: 
                        root.manager.get_screen("edit_player").update(root.team.pg)
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.pg)
                    text: "EDIT"
                    color: app.theme_cls.primary_color

                MDLabel:
                    size_hint: .85,None
                    height: "10dp"
                    text: " "
                MDLabel:
                    size_hint: .15,None
                    height: "10dp"
                    text: " "

                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: app.name2
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDLabel:
                    size_hint: .15,None
                    height: "15dp"
                    text: "SG"
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint:{"right":1, "y": 0}
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "off: " + str(app.off2) + " | def: " + str(app.deff2) + " | reb: " + str(app.reb2) + " | 3pt: " + str(app.att_three2)
                    font_size: 12
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDTextButton:
                    size_hint: .15,None
                    height:"15dp"
                    font_size: "13sp"
                    on_release: 
                        root.manager.get_screen("edit_player").update(root.team.sg)
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.sg)
                    text: "EDIT"
                    color: app.theme_cls.primary_color
                

                MDLabel:
                    size_hint: .85,None
                    height: "10dp"
                    text: " "
                MDLabel:
                    size_hint: .15,None
                    height: "10dp"
                    text: " "

                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: app.name3
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDLabel:
                    size_hint: .15,None
                    height: "15dp"
                    text: "SF"
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint:{"right":1, "y": 0}
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "off: " + str(app.off3) + " | def: " + str(app.deff3) + " | reb: " + str(app.reb3) + " | 3pt: " + str(app.att_three3)
                    font_size: 12
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDTextButton:
                    size_hint: .15,None
                    height:"15dp"
                    font_size: "13sp"
                    on_release: 
                        root.manager.get_screen("edit_player").update(root.team.sf)
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.sf)
                    text: "EDIT"
                    color: app.theme_cls.primary_color


                MDLabel:
                    size_hint: .85,None
                    height: "10dp"
                    text: " "
                MDLabel:
                    size_hint: .15,None
                    height: "10dp"
                    text: " "

                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: app.name4
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDLabel:
                    size_hint: .15,None
                    height: "15dp"
                    text: "SF"
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint:{"right":1, "y": 0}
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "off: " + str(app.off4) + " | def: " + str(app.deff4) + " | reb: " + str(app.reb4) + " | 3pt: " + str(app.att_three4)
                    font_size: 12
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDTextButton:
                    size_hint: .15,None
                    height:"15dp"
                    font_size: "13sp"
                    on_release: 
                        root.manager.get_screen("edit_player").update(root.team.pf)
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.pf)
                    text: "EDIT"
                    color: app.theme_cls.primary_color
                

                MDLabel:
                    size_hint: .85,None
                    height: "10dp"
                    text: " "
                MDLabel:
                    size_hint: .15,None
                    height: "10dp"
                    text: " "

                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: app.name5
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDLabel:
                    size_hint: .15,None
                    height: "15dp"
                    text: "SF"
                    font_size: 14
                    color: 1,1,1,1
                    pos_hint:{"right":1, "y": 0}
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "off: " + str(app.off5) + " | def: " + str(app.deff5) + " | reb: " + str(app.reb5) + " | 3pt: " + str(app.att_three5)
                    font_size: 12
                    color: 1,1,1,1
                    pos_hint: {"x": 0, "y":0}
                MDTextButton:
                    size_hint: .15,None
                    height:"15dp"
                    font_size: "13sp"
                    on_release: 
                        root.manager.get_screen("edit_player").update(root.team.c)
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.c)
                    text: "EDIT"
                    color: app.theme_cls.primary_color

            
        MD3Card:
            pos_hint: {"center_x":.5, "top":.8}
            size_hint: 1, None
            height: "250dp"
            spacing: 5
            padding: 10
            md_bg_color: .35,.35,.35,1
            radius: 10
            orientation: "vertical"
            Label:
                size_hint: .5,None
                height: "20dp"
                text: "Bench"
                font_size: 12
                color: .8,.8,.8,1
                pos_hint: {"center_x": .5, "y":0}

            GridLayout:
                cols: 2
                
                MDLabel:
                    size_hint: .85,None
                    height: "15dp"
                    text: "Coming soon.."
                    font_size: 14
                    color: .8,.8,.8,1
                    pos_hint: {"x": 0, "y":0}
                
                    





       

        MDFloatLayout:
            #size: 1 , 1
            MDIconButton:
                icon: "home-variant"
                on_release:
                    app.root.current = "start"
                    root.manager.transition.direction = "right"
            MDRaisedButton:
                text: "Coaching Settings"
                pos_hint: {"center_x": .4, "center_y": .2}
                on_release:
                    pass
            MDIconButton:
                icon: "play-box-outline"
                pos_hint: {"right": .95, "bottom": .1}
                on_release:
                    root.sim()
                    app.root.current = "results"
                    root.manager.transition.direction = "left"
            MDIconButton:
                icon: "cog"
                pos_hint: {"right": .8, "bottom": .1}
                on_release:
                    root.sim()
                    app.root.current = "settings"
                    root.manager.transition.direction = "down"



################################################################################################
################################################################################################


<SettingsPage>:
    name: "settings"
    GridLayout:
        #size_hint_y: None
        #height: self.minimum_height
        #width: self.minimum_width
        cols: 1
        spacing: "10dp"
        padding: "10dp"
        
        MDCard:
            orientation: "horizontal"
            #padding: "5dp"
            size_hint: 1, None
            height: "100dp"
            elevation: 20
            border_radius: 10
            radius: [10]
            md_bg_color: app.theme_cls.primary_dark
            BoxLayout:
                orientation: "vertical"
                MDLabel:
                    text: "Number of simulations ran on play:"
                    halign: "center"
                BoxLayout:
                    Button:
                        text: "1"
                        on_press: root.series(1)
                    Button:
                        text: "10"
                        on_press: root.series(10)
                    Button:
                        text: "100"
                        on_press: root.series(100)
                    Button:
                        text: "1,000"
                        on_press: root.series(1000)
                    Button:
                        text: "10,000"
                        on_press: root.series(10000)
        MDIconButton:
            icon: "arrow-left-bold-outline"
            on_release:
                app.root.current = "team"
                root.manager.transition.direction = "up"

                

################################################################################################
################################################################################################


<ResultsPage>:
    name: "results"
    FloatLayout:
        MDCard:
            padding: 20
            elevation: 20
            size_hint: None, None
            size_hint_x: .9
            size_hint_y: .3
            pos_hint: {'center_x': .5, 'center_y': .8}
            md_bg_color: app.theme_cls.primary_color
            MDLabel:
                text: "Hilltoppers"
                pos_hint: {'center_x': 0, 'center_y': 1}
            MDLabel:
                text: root.record
                pos_hint: {'center_x': .3, 'center_y': .5}
                font_size: 25
                color: 1,1,1,1

        
        MDCard:
            elevation: 15
            padding: 10
            #orientation: "vertical"
            size_hint_x: .9
            size_hint_y: .1
            pos_hint: {'center_x': .5, 'center_y': .55}
            md_bg_color: app.theme_cls.primary_light
            MDLabel:
                text: "Last Game"
                size_hint_y:.2
                color: 1,1,1,1
                font_size: 12
                pos_hint: {'left_x': 0, 'center_y': 1}
            MDLabel:
                text: str(root.final_score)
                pos_hint: {"center_x": .5}
                size_hint_x: None
                #size: self.texture_size
            MDRoundFlatButton:
                text: "Stats"
                pos_hint: {"right": 1}
                on_release:
                    app.root.current = "post_stats"
                    #root.manager.get_screen("post_stats").update(0)
                    root.manager.transition.direction = "left"
                    #root.update_stats(0)


########################################################################################################
########################################################################################################

    
<PostStatsPage>:
    name: "post_stats"
    BoxLayout:
        ScrollView:
            size: self.size
            GridLayout:
                size_hint_y: None
                height: self.minimum_height
                width: self.minimum_width
                cols: 1
                spacing: "10dp"
                padding: "10dp"
                MDLabel:
                    halign: "center"
                    color: app.theme_cls.primary_dark
                    font_size: 22
                    text: root.score
                
                MD3Card:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name1
                        secondary_text: "P: [color=#FFFFFF]" + root.stats1 + "[/color]  R: [color=#FFFFFF]" + root.rebs1
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg1 + "[/color]  3P: [color=#FFFFFF]" + root.threes1
                        ImageLeftWidget:
                            source: "image1.png"

                MD3Card:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name2
                        secondary_text: "P: [color=#FFFFFF]" + root.stats2 + "[/color]  R: [color=#FFFFFF]" + root.rebs2
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg2 + "[/color]  3P: [color=#FFFFFF]" + root.threes2
                        ImageLeftWidget:
                            source: "image2.png"

                MD3Card:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name3
                        secondary_text: "P: [color=#FFFFFF]" + root.stats3 + "[/color]  R: [color=#FFFFFF]" + root.rebs3
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg3 + "[/color]  3P: [color=#FFFFFF]" + root.threes3
                        ImageLeftWidget:
                            source: "image3.png"

                MD3Card:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name4
                        secondary_text: "P: [color=#FFFFFF]" + root.stats4 + "[/color]  R: [color=#FFFFFF]" + root.rebs4
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg4 + "[/color]  3P: [color=#FFFFFF]" + root.threes4
                        ImageLeftWidget:
                            source: "image4.png"
            
                MD3Card:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name5
                        secondary_text: "P: [color=#FFFFFF]" + root.stats5 + "[/color]  R: [color=#FFFFFF]" + root.rebs5
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg5 + "[/color]  3P: [color=#FFFFFF]" + root.threes5
                        ImageLeftWidget:
                            source: "image5.png"

                MDRaisedButton:
                    text:  root.opp_name + "' Stats"
                    pos_hint: {"right": 1}
                    on_release:
                        root.update(root.get_n())
                    
                            
    MDIconButton:
        icon:"arrow-left-bold-outline"
        on_release:
            app.root.current = "results"
            root.manager.transition.direction = "right"
            #root.update(root.get_n())
            
            
            


<InfoPage>:
    name: "info"
    BoxLayout:
        ScrollView:
            #size: self.size
            MDLabel:
                size_hint_y: None
                text_size: self.width, None
                height: self.texture_size[1]
                text_size: self.width, None
                padding: 12,12
                font_size: 15
                text: root.text1
    MDIconButton:
        icon: "home-variant"
        icon_size: "96sp"
        icon_color: app.theme_cls.primary_color
        on_release:
            app.root.current = "start"
            root.manager.transition.direction = "down"
            


<EditPage>:
    name: "edit_player"
    GridLayout:
        cols: 1
        size_hint: 1,1
        spacing: "10dp"
        padding: "8dp"
        
        MD3Card:
            size_hint: 1, None
            height: "60dp"
            padding: 10
            md_bg_color: .9,.9,.9,1
            MDTextField:
                color: 0,0,0,1
                id: "player_name"
                on_text: root.on_name_input(self)
                hint_text: root.player_name
                helper_text: "Player Name"
                helper_text_mode: "persistent"
                max_text_length: 25
                
                

        MD3Card:
            orientation: "vertical"
            size_hint: 1, None
            height: "60dp"
            padding: 10
            spacing: 5
            md_bg_color: app.theme_cls.primary_light
            BoxLayout:
                MDLabel:
                    text: "Offense"
                    font_size: 14
                    size_hint:.32, None
                    height: "20"
                MDSlider:
                    id: "off_slider"
                    on_value: root.on_off_slider(self)
                    hint_bg_color: 1,1,1,1
                    max:99
                    value: 70
            MDLabel:
                text: "The \"offense\" attribute currently is associated with 2-pt shots and the likelihood of commiting a turnover." 
                color: 0,0,0,.5
                italic: True
                font_size: 12
           
        MD3Card:
            orientation: "vertical"
            size_hint: 1, None
            height: "60dp"
            padding: 10
            spacing: 5
            md_bg_color: app.theme_cls.primary_light
            BoxLayout:
                MDLabel:
                    text: "Defense"
                    font_size: 14
                    size_hint:.32, None
                    height: "20"
                MDSlider:
                    id: "deff_slider"
                    on_value: root.on_deff_slider(self)
                    hint_bg_color: 1,1,1,1
                    max: 99
                    value: 70
            MDLabel:
                text: "The \"defense\" attribute currently is associated with defending 2 & 3 pt shots as well as the likelihood of creating a turnover." 
                color: 0,0,0,.5
                italic: True
                font_size: 12

        MD3Card:
            orientation: "vertical"
            size_hint: 1, None
            height: "60dp"
            padding: 10
            spacing: 5
            md_bg_color: app.theme_cls.primary_light
            BoxLayout:
                MDLabel:
                    text: "Rebounding"
                    font_size: 14
                    size_hint:.32, None
                    height: "20"
                MDSlider:
                    id: "reb_slider"
                    on_value: root.on_rebounding_slider(self)
                    hint_bg_color: 1,1,1,1
                    max: 99
                    value: 70
            MDLabel:
                text: "\"Rebounding\", along with \"height\", increases the chance of this player to rebound a missed shot."
                color: 0,0,0,.5
                italic: True
                font_size: 12

        MD3Card:
            orientation: "vertical"
            size_hint: 1, None
            height: "50dp"
            padding: 10
            spacing: 5
            md_bg_color: app.theme_cls.primary_light
            BoxLayout:
                MDLabel:
                    text: "Long Range"
                    font_size: 13
                    size_hint:.32, None
                    height: "20"
                MDSlider:
                    id: "long_range_slider"
                    on_value: root.on_three_slider(self)
                    hint_bg_color: 1,1,1,1
                    max: 99
                    value: 70
            MDLabel:
                text: "\"Long Range\" is how good the player is at shooting threes."
                color: 0,0,0,.5
                italic: True
                font_size: 12

        MD3Card:
            orientation: "vertical"
            size_hint: 1, None
            height: "86dp"
            padding: 10
            spacing: 5
            elevation: 20
            md_bg_color: app.theme_cls.primary_light
            MDLabel:
                text: "Long Range Bias"
                pos_hint: {"center_x": .5, "bottom":0} 
                font_size: 14
                size_hint:.5, None
                height: "14dp"
            MDSlider:
                id: "bias_slider"
                on_value: root.on_three_dist_slider(self)
                hint_bg_color: 1,1,1,1
                value: 15
            MDLabel:
                text: "\"Long Range Bias\" is the percentage of this player\'s shots that will be three pointers."
                color: 0,0,0,.5
                italic: True
                font_size: 12


    MDLabel:
        size_hint: .22, None
        height: "20dp"
        pos_hint: {"right": 1, "top": .99}
        text: "Starting " + root.player_position
        font_size: 12

    MDRoundFlatIconButton:
        icon: "check"
        text: "Accept"
        pos_hint: {"x": .5, "y": .03}
        on_release:
            root.save()
            app.update(app.main_team, app.secondary_team)
            app.root.current = "team"
            root.manager.transition.direction = "down"
    MDRoundFlatButton:
        text: "Cancel"
        pos_hint: {"right": .47, "y": .03}
        on_release:
            app.root.current = "team"
            root.manager.transition.direction = "down"
            print(root.off_slider)