#: import get_color_from_hex kivy.utils.get_color_from_hex
WindowManager:
    StartPage:
    TeamPage:
    ResultsPage:
    PostStatsPage:
    InfoPage:
    SettingsPage:
    EditPage:

<StartPage>:
    name: "start"
    MDLabel:
        text: "D1 Hoops"
        font_size: 60
        color: app.theme_cls.primary_dark
        bold: True
        italic: True
        outline_color: app.theme_cls.primary_light
        outline_width: 3
        halign: "center"

    MDLabel:
        text: "alpha 0.1.0"
        pos_hint: {"center_x": 1.06, "center_y": 0.43}

    MDIconButton:
        icon: "information-outline"
        icon_size: "50sp"
        icon_color: app.theme_cls.primary_color
        on_release:
            app.root.current = "info"
            root.manager.transition.direction = "up"

    MDRaisedButton:
        text: "New Game"
        pos_hint: {"center_x": 0.5, "center_y": 0.18}
        on_release:
            app.root.current = "team"
            root.manager.transition.direction = "left"
    MDRaisedButton:
        text: "Load Game"
        pos_hint: {"center_x": 0.5, "center_y": 0.1}





<TeamPage>:
    name: "team"
    BoxLayout:
        background_color: (45/255), (45/255), (50/255), .88
        canvas.before:
            Color:
                rgba: self.background_color
            Rectangle:
                size: self.size
                pos: self.pos
        orientation: "horizontal"
        BoxLayout:
            orientation: "vertical"
            Label:
                background_color: (100/255), (100/255), (105/255), 1
                canvas.before:
                    Color:
                        rgba: self.background_color
                    Rectangle:
                        size: self.size
                        pos: self.pos
                text: "Create your team"
                font_size: 30
            BoxLayout:
                id: pg1
                orientation: "horizontal"
                TextInput:
                    id: pg1_name
                    size_hint: .4, .4
                    hint_text: "Dee Dee Smith"
                    multiline: False
                    on_text: root.pg1_name_val(self)
                MDRaisedButton:
                    text: "Advanced Edit"
                    on_release:
                        app.root.current = "edit_player"
                        root.manager.transition.direction = "up"
                        root.edit_player(root.team.pg)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: pg_off_label
                        text: root.pgoff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 75
                        on_value: root.pg1_off_val(self)
                        orientation: "horizontal"
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: pg_deff_label
                        text: root.pgdeff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 80
                        on_value: root.pg1_deff_val(self)
                        orientation: "horizontal"
                    
            BoxLayout:
                id: sg1
                orientation: "horizontal"
                TextInput:
                    id: sg1_name
                    size_hint: .4, .4
                    hint_text: "Roger Huntely"
                    multiline: False
                    on_text: root.sg1_name_val(self)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: sg_off_label
                        text: root.sgoff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 61
                        on_value: root.sg1_off_val(self)
                        orientation: "horizontal"
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: sg_deff_label
                        text: root.sgdeff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 80
                        on_value: root.sg1_deff_val(self)
                        orientation: "horizontal"

            BoxLayout:
                id: sf1
                orientation: "horizontal"
                TextInput:
                    id: sf1_name
                    size_hint: .4, .4
                    hint_text: "Malcolm Smith"
                    multiline: False
                    on_text: root.sf1_name_val(self)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: sf_off_label
                        text: root.sfoff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 61
                        on_value: root.sf1_off_val(self)
                        orientation: "horizontal"
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: sf_deff_label
                        text: root.sfdeff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 80
                        on_value: root.sf1_deff_val(self)
                        orientation: "horizontal"
        
            BoxLayout:
                id: pf1
                orientation: "horizontal"
                TextInput:
                    id: pf1_name
                    size_hint: .4, .4
                    hint_text: "George Fant"
                    multiline: False
                    on_text: root.pf1_name_val(self)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: pf_off_label
                        text: root.pfoff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 79
                        on_value: root.pf1_off_val(self)
                        orientation: "horizontal"
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: pf_deff_label
                        text: root.pfdeff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 80
                        on_value: root.pf1_deff_val(self)
                        orientation: "horizontal"

            BoxLayout:
                id: c1
                orientation: "horizontal"
                TextInput:
                    id: c1_name
                    size_hint: .4, .4
                    hint_text: "Alex Poythresse"
                    multiline: False
                    on_text: root.c1_name_val(self)
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: c_off_label
                        text: root.coff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 88
                        on_value: root.c1_off_val(self)
                        orientation: "horizontal"
                BoxLayout:
                    orientation: "vertical"
                    size_hint: .3,1
                    Label:
                        id: c_deff_label
                        text: root.cdeff
                    MDSlider:
                        id: my_slider
                        size_hint: 1,.5
                        min: 1
                        max: 99
                        value: 80
                        on_value: root.c1_deff_val(self)
                        orientation: "horizontal"
            #MDLabel:
                #text: "Team Overall Rating: " + str(root.overall) 
            #MDLabel:
                #text: "Opponent Overall Rating: " + str(root.overall2) 

            MDFloatLayout:
                #size: 1 , 1
                MDIconButton:
                    icon: "home-variant"
                    on_release:
                        app.root.current = "start"
                        root.manager.transition.direction = "right"
                MDRaisedButton:
                    text: "Coaching Settings"
                    pos_hint: {"center_x": .4, "center_y": .2}
                    on_release:
                        pass
                MDIconButton:
                    icon: "play-box-outline"
                    pos_hint: {"right": .95, "bottom": .1}
                    on_release:
                        root.sim()
                        app.root.current = "results"
                        root.manager.transition.direction = "left"
                MDIconButton:
                    icon: "cog"
                    pos_hint: {"right": .8, "bottom": .1}
                    on_release:
                        root.sim()
                        app.root.current = "settings"
                        root.manager.transition.direction = "down"


<SettingsPage>:
    name: "settings"
    GridLayout:
        #size_hint_y: None
        #height: self.minimum_height
        #width: self.minimum_width
        cols: 1
        spacing: "10dp"
        padding: "10dp"
        
        MDCard:
            orientation: "horizontal"
            #padding: "5dp"
            size_hint: 1, None
            height: "100dp"
            elevation: 20
            border_radius: 10
            radius: [10]
            md_bg_color: app.theme_cls.primary_dark
            BoxLayout:
                orientation: "vertical"
                MDLabel:
                    text: "Number of simulations ran on play:"
                    halign: "center"
                BoxLayout:
                    Button:
                        text: "1"
                        on_press: root.series(1)
                    Button:
                        text: "10"
                        on_press: root.series(10)
                    Button:
                        text: "100"
                        on_press: root.series(100)
                    Button:
                        text: "1,000"
                        on_press: root.series(1000)
                    Button:
                        text: "10,000"
                        on_press: root.series(10000)
        MDIconButton:
            icon: "arrow-left-bold-outline"
            on_release:
                app.root.current = "team"
                root.manager.transition.direction = "up"

                

<ResultsPage>:
    name: "results"
    FloatLayout:
        MDCard:
            padding: 20
            elevation: 20
            size_hint: None, None
            size_hint_x: .9
            size_hint_y: .3
            pos_hint: {'center_x': .5, 'center_y': .8}
            md_bg_color: app.theme_cls.primary_color
            MDLabel:
                text: "Hilltoppers"
                pos_hint: {'center_x': 0, 'center_y': 1}
            MDLabel:
                text: root.record
                pos_hint: {'center_x': .3, 'center_y': .5}
                font_size: 25
                color: 1,1,1,1

        
        MDCard:
            elevation: 15
            padding: 10
            #orientation: "vertical"
            size_hint_x: .9
            size_hint_y: .1
            pos_hint: {'center_x': .5, 'center_y': .55}
            md_bg_color: app.theme_cls.primary_light
            MDLabel:
                text: "Last Game"
                size_hint_y:.2
                color: 1,1,1,1
                font_size: 12
                pos_hint: {'left_x': 0, 'center_y': 1}
            MDLabel:
                text: str(root.final_score)
                pos_hint: {"center_x": .5}
                size_hint_x: None
                #size: self.texture_size
            MDRoundFlatButton:
                text: "Stats"
                pos_hint: {"right": 1}
                on_release:
                    app.root.current = "post_stats"
                    root.manager.transition.direction = "left"
                    root.update_stats(0)
    
    
<PostStatsPage>:
    name: "post_stats"
    BoxLayout:
        ScrollView:
            size: self.size
            GridLayout:
                size_hint_y: None
                height: self.minimum_height
                width: self.minimum_width
                cols: 1
                spacing: "10dp"
                padding: "10dp"
                MDLabel:
                    halign: "center"
                    color: app.theme_cls.primary_dark
                    font_size: 22
                    text: root.score
                
                MDCard:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name1
                        secondary_text: "P: [color=#FFFFFF]" + root.stats1 + "[/color]  R: [color=#FFFFFF]" + root.rebs1
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg1 + "[/color]  3P: [color=#FFFFFF]" + root.threes1
                        ImageLeftWidget:
                            source: "image1.png"

                MDCard:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name2
                        secondary_text: "P: [color=#FFFFFF]" + root.stats2 + "[/color]  R: [color=#FFFFFF]" + root.rebs2
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg2 + "[/color]  3P: [color=#FFFFFF]" + root.threes2
                        ImageLeftWidget:
                            source: "image2.png"

                MDCard:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name3
                        secondary_text: "P: [color=#FFFFFF]" + root.stats3 + "[/color]  R: [color=#FFFFFF]" + root.rebs3
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg3 + "[/color]  3P: [color=#FFFFFF]" + root.threes3
                        ImageLeftWidget:
                            source: "image3.png"

                MDCard:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name4
                        secondary_text: "P: [color=#FFFFFF]" + root.stats4 + "[/color]  R: [color=#FFFFFF]" + root.rebs4
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg4 + "[/color]  3P: [color=#FFFFFF]" + root.threes4
                        ImageLeftWidget:
                            source: "image4.png"
            
                MDCard:
                    orientation: "horizontal"
                    #padding: "8dp"
                    size_hint: 1, None
                    height: "82dp"
                    elevation: 20
                    border_radius: 10
                    radius: [10]
                    md_bg_color: app.theme_cls.primary_color
                    ThreeLineAvatarIconListItem:
                        text: root.name5
                        secondary_text: "P: [color=#FFFFFF]" + root.stats5 + "[/color]  R: [color=#FFFFFF]" + root.rebs5
                        tertiary_text: "FG: [color=#FFFFFF]" + root.fg5 + "[/color]  3P: [color=#FFFFFF]" + root.threes5
                        ImageLeftWidget:
                            source: "image5.png"

                MDRaisedButton:
                    text:  root.opp_name + "' Stats"
                    pos_hint: {"right": 1}
                    on_release:
                        #app.root.current = "post_stats"
                        #root.manager.transition.direction = "left"
                        root.update(root.get_n())
                    
                            
    MDIconButton:
        icon:"arrow-left-bold-outline"
        on_release:
            app.root.current = "results"
            root.manager.transition.direction = "right"
            


<InfoPage>:
    name: "info"
    BoxLayout:
        ScrollView:
            #size: self.size
            MDLabel:
                size_hint_y: None
                text_size: self.width, None
                height: self.texture_size[1]
                text_size: self.width, None
                padding: 12,12
                font_size: 15
                text: root.text1
    MDIconButton:
        icon: "home-variant"
        icon_size: "96sp"
        icon_color: app.theme_cls.primary_color
        on_release:
            app.root.current = "start"
            root.manager.transition.direction = "down"
            


<EditPage>:
    name: "edit_player"
    GridLayout:
        cols: 1
        size_hint: 1,1
        MDTextField:
            hint_text: "Dee Dee Smith"
            helper_text: "Player Name"
            helper_text_mode: "persistent"
            max_text_length: 25
        MDLabel:
            text: "Offense:"

